# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reproductionframework < Formula
  desc "Reproduction Framework CLI tool"
  homepage "https://github.com/kkignasiak98/ReproductionFramework"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.6.0/ReproductionFramework_Darwin_x86_64.tar.gz"
      sha256 "e2b43588a348b611d1879a54217f17bf47ae31e96a300da9c785ee82d1257baf"

      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.6.0/ReproductionFramework_Darwin_arm64.tar.gz"
      sha256 "e97d94fc7fbfabfb0793ff82ebc62e0d4e0dfcf8d997380c9afc4555206a126a"

      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.6.0/ReproductionFramework_Linux_x86_64.tar.gz"
      sha256 "55549d2e0e09abc036719302d9d412dca77750562e618921f24f480fbf0eb6e1"
      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.6.0/ReproductionFramework_Linux_arm64.tar.gz"
      sha256 "5f7c8526228e03a4db6ad7204f215fef778f32bb824f6c156263cf1dfaa1ad31"
      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
  end
end
