# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reproductionframework < Formula
  desc "Reproduction Framework CLI tool"
  homepage "https://github.com/kkignasiak98/ReproductionFramework"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.5.1/ReproductionFramework_Darwin_x86_64.tar.gz"
      sha256 "b62046c9a72509998920374e94c521db12728cd0803ff340f6141402ea7c6b76"

      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.5.1/ReproductionFramework_Darwin_arm64.tar.gz"
      sha256 "cfadeeefa85ef9eb18bc02c68e559c2f7d57d43d94ed608c96d70d9532129a3b"

      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.5.1/ReproductionFramework_Linux_x86_64.tar.gz"
      sha256 "f3e8712b13ae8d0e8fa83db2d76cb4563293033c633caab80e962991761bd84f"
      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.5.1/ReproductionFramework_Linux_arm64.tar.gz"
      sha256 "eb83954bea449f3b603ddc68c95262fa69cb6fc1f903bbb67d9abbffb9fab4f8"
      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
  end
end
