# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reproductionframework < Formula
  desc "Reproduction Framework CLI tool"
  homepage "https://github.com/kkignasiak98/ReproductionFramework"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.7.0/ReproductionFramework_Darwin_x86_64.tar.gz"
      sha256 "83d0a5e468d62bf7cd1637a5948431138ac30290c31eabe6eb068a785a025fff"

      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.7.0/ReproductionFramework_Darwin_arm64.tar.gz"
      sha256 "3fac2021c5a71f9e6d18e7ce995cfeb4d6bb3473c973c879b0f2f458035cd7d6"

      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.7.0/ReproductionFramework_Linux_x86_64.tar.gz"
      sha256 "4961c1487ce0de6e9ca3e83b3caa92f8a91df3ea7a5ce48451bafae5fd392a87"
      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kkignasiak98/ReproductionFramework/releases/download/v0.7.0/ReproductionFramework_Linux_arm64.tar.gz"
      sha256 "62d8bd42dde68bfe1bab1fb8d27dd6a3cdbd56255504f613c83ea2b7a9cb1565"
      define_method(:install) do
        bin.install "ReproductionFramework"
      end
    end
  end
end
